# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant version 2.3.0 or higher is required
# Use VirtualBox version 6.1 or higher
Vagrant.require_version ">= 2.3.0"

Vagrant.configure("2") do |config|
	config.vm.box_download_insecure = true
	config.vm.box = "itc/itc-ubuntu-mate-20.04-amd64"

	config.vm.provider "virtualbox" do |vb|
		vb.name = "OSGP Development"
		vb.gui = true
		vb.cpus = "2"
		vb.memory = "8192"

		# Disable 3d acceleration because some programs crash on it.
		vb.customize ["modifyvm", :id, "--accelerate3d", "off"]

		# Enabling copy/paste to/from VM
		vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
		vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]

		# Add cdrom
		vb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--port", "0", "--device", "0", "--type", "dvddrive", "--medium", "emptydrive"]
	end

	config.vm.hostname="dev-box"

	config.vm.provision "shell", inline: <<-SHELL
		# Clone config repo for user Vagrant
		apt-get -o DPkg::Options::=--force-confdef install -y git;
		su vagrant -c "mkdir -p ~/repos/OSGP";
		su vagrant -c "git clone -b "development" https://github.com/OSGP/Config.git ~/repos/OSGP/Config 2>&1";

		# Install puppet
		su vagrant -c "/home/vagrant/repos/OSGP/Config/puppet/install-puppet.sh";

		# Trigger puppet installation
		su vagrant -c "cd /home/vagrant/repos/OSGP/Config/puppet/;/home/vagrant/repos/OSGP/Config/puppet/run-puppet.sh";
	SHELL

	# Provision some user specific settings/configuration/packages
	user_config_file=".user-dev-box.sh"
	if File.file?(File.join(Dir.home, user_config_file))
		config.vm.provision "shell", path: File.join(Dir.home, user_config_file)
	end

end
